version: '3.7'
services:
  socat:
    image: nickadam/socat:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    environment:
      SOCAT_CONFIG: |
        TCP4-LISTEN:8080,fork,reuseaddr TCP4:www.google.com:80
        TCP4-LISTEN:8081,fork,reuseaddr TCP4:www.bing.com:80